export const siteMetaData = {
  title: "Project: Next.js Blog With Tailwind CSS and Contentlayer",
  author: "edward-designer",
  headerTitle: "Next.js Blog",
  description: "A blog created with Next.js, Tailwind.css and contentlayer.",
  language: "en-us",
  theme: "system",
  siteUrl: "https://nedward-nextjs-contentlayer.vercel.app",
  siteLogo: "/logo.png",
  socialBanner: "/social-banner.png",
  email: "edward.chung.designer@gmail.com",
  github: "https://github.com/edward-designer",
  twitter: "https://twitter.com/edwebdeveloper",
  facebook: "https://facebook.com",
  youtube: "https://youtube.com/",
  linkedin: "https://www.linkedin.com/in/edwardchungweb/",
  locale: "en-UK",
};
